### ISSUE TITLE
Game play stuck if dice is pressed accidentally before adding players

### ISSUE THREAD

**Issue by prabushitha** [vishalchawla/online-snake-and-ladder-game-html5-canvas#1]
Steps:
1) Load the game
2) Click on dice
3) Add a player
4) Click on dice 

Expected behavior: Dice should roll 
Actual behavior: Dice is not rolling. The game is stuck there.

**Comment by vishalchawla** [comment]
Thanks @prabushitha, happy to see your contribution :)
